using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using UnityEngine.UI;

public class CameraInterface : MonoBehaviour
{
    public Player player;
    public GameObject enterButton;
    public GameObject eButton;
    public GameObject eButtonHigh;
    public GameObject mouseButton;
    public GameObject cButton;
    public TextMeshProUGUI progress;
    public Camera mainCamera;
    public Camera uicam;
    public Canvas hudCanvas;
    public Canvas menuCanvas;
    public Canvas editorCanvas;
    public Canvas loadingCanvas;
    public Canvas transitionCanvas;
    public Canvas questionnaireCanvas;
    public Canvas popUpCanvas;
    public GameObject webDebugWindow;
    public TerminalWindow terminalWindow;
    public FollowPlayer followPlayer;
    public CameraOrbit cameraOrbit;
    public GameObject thinkCloud;
    public GameObject nameCloud;
    public GameObject ifParent;
    public GameObject msgBox;
    public SoapBar soapBar;
    public Image expBar;
    public Image safeBar;
    public GameObject inventory;
    public TextMeshProUGUI level;
    public TextMeshProUGUI likesText;
    public GameObject phone;
    public GameObject battery;
    public Image notBG;
    public TextMeshProUGUI notText;
    public AudioSource FX;
    public AudioSource music;
    public AudioManager audioManager;
    public TextMeshProUGUI crystalCounterText;
    public Hint hint;
    public TextMeshProUGUI timerText;
    public TextMeshProUGUI currentID;
    public GameObject glider;
    public GameObject rocket;
    public WordByWord byWord;
    public GameObject graffitiTutorialContainer;
    public GameObject dialogueTutorialContainer;
    public GameObject star;
    public GameObject youSavedAStudent;
    public GameObject titleScreen;
    public GameObject okCircle;
    public GameObject touchIcon;
    public GameObject participateButton;
    public GameObject gameOver;
    public TextMeshProUGUI demoMode;
    public GameObject ouch;
    public GameObject almost;
    public GameObject goodJob;
    public GameObject wellDone;
    public GameObject perfect;
}
